final Map<String, String> enUs = {
  'title' : 'SYSTEM LOGIN',
  'userNameFormatError' : "USERNAME FORMAT ERROE",
  'userPasswordFormatError' : "USERPASSWORD FORMAT ERROE",
  'userName' : "USERNAME",
  'userPassword' : "USERPASSWORD",
  'singIn' : 'SINGIN',
  'userNameHint' :     'Account name: letters or numbers',
  'userPasswordHint' : 'Password:     less than ten digits',
  'frontPage' : 'FRONTPAGE',
  'setUp' : 'SETUP',
  'components' : 'COMPONENTS',
  'otherLogin' : 'THIRD PARTY LOGIN',
  'langZh' : '中文',
  'langEn' : 'ENGLISH',
  'darkTheme' : 'DARK',
  'lightTheme' : 'LITHT',
  'lightGreen' : 'lIGHTGREEN',
  'lightYellow' : 'LIGHTYELLOW',
  'lightRed' : 'LIGHTRED',
  'lightBlack' : 'LIGHTBLACK',
  'lightWhite' : 'LIGHTWHITE',
};