final Map<String, String> zhCn = {
  'title' : '系统登录',
  'userNameFormatError' : "用户名格式错误",
  'userPasswordFormatError' : "用户密码格式错误",
  'userName' : "用户名",
  'userPassword' : "用户密码",
  'singIn' : '登录',
  'userNameHint' :'账号：字母或者数字',
  'userPasswordHint' : '密码：小于十位的数字',
  'frontPage' : '首页',
  'setUp' : '设置',
  'components' : '组件',
  'otherLogin' : '第三方登录',
  'langZh' : '中文',
  'langEn' : 'ENGLISH',
  'darkTheme' : '黑夜',
  'lightTheme' : '白天',
  'lightGreen' : '明绿',
  'lightYellow' : '明黄',
  'lightRed' : '明红',
  'lightBlack' : '明黑',
  'lightWhite' : '明白',

};